#!/bin/bash

# User Configuration Section
# --------------------------

root="domain.com"
wp_user="john.smith"
logfile="cli_script_logfile_softcli.log"

# --------------------------
# End User Configuration Section


# Error checking to makes ure we have sane values - probably a better way to do this
# No argument, return usage
if [ -z "$1" ] || ! [[ "$1" =~ ^(install|remove|otlogin|stage|makelive|list)$ ]]; then
	echo "Please use $0 install <subdomain> to create the new site or";
	echo "Please use $0 remove <inst_id> to remove an existing site or ";
	echo "Please use $0 otlogin <inst_id> to create a one time login for a site or ";
	echo "Please use $0 stage <inst_id> <subdomain> to create a staging site from an existing id on a new subdomain or ";
	echo "Please use $0 makelive <inst_id> to push a copy of staging to the live site it was created from or ";
	echo "Please use $0 list to list existing installations";
	exit;
fi

# We have at least one argument, see if it is list, if not, we have additional checking to do
# We are listing instances:
if [ "$1" = "list" ]; then
	echo "Listing Installations...";
	php /usr/local/cpanel/whostmgr/docroot/cgi/softaculous/cli.php --list_ins
	exit;
fi

# If it wasn't list, and we don't have a 2nd argument and the first command is install
if [ -z "$2" ] && [ "$1" = "install" ]; then
	echo "Missing subdomain"
	echo "Please use $0 install <subdomain> to create the new site";
	exit;
fi

# Source the current password for the account and the generic WP login password since we'll need it for installation or removal of an install
. ~/.pw

#Give the log file a little whitespace if we thing we're gonna run a command and a timestamp for good measure
echo >> $logfile
date >> $logfile

# We are installing a new instance:
if [ "$1" = "install" ]; then
	echo "Installing WP on subdomain $2";
	# Create the subdomain in cpanel so softaculous can access it
	echo "Creating subdomain $2.$root"
	uapi SubDomain addsubdomain domain=$2 rootdomain=$root dir=$2.$root >> $logfile
	echo "Invoking AutoSSL (make take a few minutes for the cert to generate)"
	uapi SSL start_autossl_check >> $logfile
	echo "Invoking Softactulous Installation of WP"
	# Install wordpress on the subdomain
	php /usr/local/cpanel/whostmgr/docroot/cgi/softaculous/cli.php --install --panel_user=`whoami` --panel_pass=$CPW --soft=26 --softdomain=$2.$root --admin_username=$wp_user --admin_pass=$WPPW --softproto='https://'
	inst_id=`php /usr/local/cpanel/whostmgr/docroot/cgi/softaculous/cli.php --list_ins | grep $2.$root | awk '{print $2}'`
	# attempt to validate we have a good id
	if ! [[ $inst_id =~ $idre ]] ; then
		echo "Unable to find valid ID to generate One Time Login, skipping..."
		exit
	fi
	echo "Attempting to generate one time login url for ID: $inst_id"
	curl -s "https://`whoami`:$CPW@cpanel03.dtsrv.net:2083/frontend/paper_lantern/softaculous/index.live.php?act=sign_on&insid=$inst_id&autoid=abcdefghijklmnopqrstuvwxyz0123456789&api=json" | sed -n 's|.*"sign_on_url":"\([^"]*\)".*|\1|p' | sed  's|\\||g'
	echo
	echo
	exit;
fi

# Regex for valid ID for checking later
idre='^26_[0-9]{5}$'

#If we are missing or have an invalid installation id, we verify and detail the same command with subcommand again, just detailing usage
if ! [[ $2 =~ $idre ]] ; then
	echo "Missing or invalid installation ID: $2"
	echo "Please use $0 $1 <inst_id> to push a copy of staging to the live site it was created from";
	exit;
fi

# if we are using staging, we need a 3rd argument
if [ -z "$3" ] && [ "$1" = "stage" ]; then
	echo "Missing subdomain"
	echo "Please use $0 stage <inst_id> <subdomain> to create a staging site from an existing id to a new subdomain ";
	exit;
fi

# We know we have a valid install ID on $2 at this point, and if it requires a 3rd for staging, it exists, so lets just check which command we got and go nutz
if [ "$1" = "otlogin" ]; then
	echo "Attempting to generate one time login url for ID: $2"
	echo 
	curl -s "https://`whoami`:$CPW@cpanel03.dtsrv.net:2083/frontend/paper_lantern/softaculous/index.live.php?act=sign_on&insid=$2&autoid=abcdefghijklmnopqrstuvwxyz0123456789&api=json" | sed -n 's|.*"sign_on_url":"\([^"]*\)".*|\1|p' | sed  's|\\||g'
	echo
	echo 
	exit;
fi

# We are pusing a staging site to it's live counterpart
if [ "$1" = "makelive" ]; then
	echo "Attempting to push staging on id $2 to its live version"
	read -p "Are you sure (y/n)? " -n 1 -r
	echo    # (optional) move to a new line
	if [[ ! $REPLY =~ ^[Yy]$ ]]; then
	    echo "Bailing!..."
	    exit
	fi
	curl -s -d "softsubmit=1" "https://`whoami`:$CPW@cpanel03.dtsrv.net:2083/frontend/paper_lantern/softaculous/index.live.php?act=pushtolive&insid=$2&api=json" >> $logfile
	# Another background process, so lets give it a second to complete. 
	sleep 3
	echo "Staging to live migration has begun, depending on the site of the site, it may be done."
	exit;
fi

# We are removing an instance:
if [ "$1" = "remove" ]; then
	echo "Removing Installation id $2 (please note that we are not able to remove the subdomain/folder at this time)";
	read -p "Are you sure (y/n)? " -n 1 -r
	echo    # (optional) move to a new line
	if [[ ! $REPLY =~ ^[Yy]$ ]]; then
	    echo "Bailing!..."
	    exit
	fi
	# UAPI version of delsubdomain doesn't exist yet... You'll have to clean them up in cPanel directly -- 1/20/22 - Russ
	curl -s -d "removeins=1" -d "remove_dir=1" -d "remove_datadir=1" -d "remove_db=1" -d "remove_dbuser=1" "https://`whoami`:$CPW@cpanel03.dtsrv.net:2083/frontend/paper_lantern/softaculous/index.live.php?act=remove&insid=$2&api=json" >> $logfile
	echo "Installation $2 removed"
	echo 
	exit;
fi

# We are creating a staging environment from an instance:
if [ "$1" = "stage" ]; then
	echo "Staging installation $2 to Installing WP on subdomain $3";
	# Create the subdomain in cpanel so softaculous can access it
	echo "Creating subdomain $3.$root"
	uapi SubDomain addsubdomain domain=$3 rootdomain=$root dir=$3.$root >> $logfile
	echo "Invoking AutoSSL (make take a few minutes for the cert to generate)"
	uapi SSL start_autossl_check >> $logfile
	echo "Invoking Softactulous Clone of ID $2"
	# Clone existing wordpress on to the new subdomain
	curl -s -d "softproto=3" -d "softsubmit=1" -d "softdomain=$3.$root" -d 'softdirectory=' -d "softdb=st${2: -5}" "https://`whoami`:$CPW@cpanel03.dtsrv.net:2083/frontend/paper_lantern/softaculous/index.live.php?act=staging&insid=$2&api=json" >> $logfile
	# Lets give it a moment before attempting to generate the OT signon, as this is a background process and if the site is large, there may be a delay in creating it
	sleep 3
	echo "Generating Single Use Signon:"
	inst_id=`php /usr/local/cpanel/whostmgr/docroot/cgi/softaculous/cli.php --list_ins | grep $3.$root | awk '{print $2}'`
	if ! [[ $inst_id =~ $idre ]] ; then
		echo "Unable to find valid ID to generate One Time Login, skipping..."
		exit
	fi
	echo "Attempting to generate one time login url for ID: $inst_id"
	curl -s "https://`whoami`:$CPW@cpanel03.dtsrv.net:2083/frontend/paper_lantern/softaculous/index.live.php?act=sign_on&insid=$inst_id&autoid=abcdefghijklmnopqrstuvwxyz0123456789&api=json" | sed -n 's|.*"sign_on_url":"\([^"]*\)".*|\1|p' | sed  's|\\||g'
	echo
	echo
	exit;
fi
